name: cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
# featureGates:
#   "JobPodFailurePolicy": true 
#  "KubeletInUserNamespace": true
nodes:
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker